name=assetto-corsa-udp
version=1.0.1
author=MacManley
maintainer=MacManley
sentence=Assetto Corsa UDP telemetry parser for Arduino (ESP8266/ESP32)
paragraph=Parses Assetto Corsa UDP telemetry packets and provides simple example sketches for use with ESP8266 and ESP32.
category=Communication
url=https://github.com/MacManley/assetto-corsa-udp
architectures=*
